// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbuWVslV3Abl91Qohjdlk1a45Htood05A',
    appId: '1:902496285809:web:26a8f3fbc4c98576e957d0',
    messagingSenderId: '902496285809',
    projectId: 'safe-go-98e43',
    authDomain: 'safe-go-98e43.firebaseapp.com',
    databaseURL: 'https://safe-go-98e43-default-rtdb.firebaseio.com',
    storageBucket: 'safe-go-98e43.appspot.com',
    measurementId: 'G-E3FESSW1C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8tBUhDPjA4fS3l--ns0kWBQXlqs5YGps',
    appId: '1:902496285809:android:cd6bc77ee9cb73ede957d0',
    messagingSenderId: '902496285809',
    projectId: 'safe-go-98e43',
    databaseURL: 'https://safe-go-98e43-default-rtdb.firebaseio.com',
    storageBucket: 'safe-go-98e43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtZNhWv03Kl_da_vUoevW9RW52Vp7Gk9w',
    appId: '1:902496285809:ios:639c431e4087dbf7e957d0',
    messagingSenderId: '902496285809',
    projectId: 'safe-go-98e43',
    databaseURL: 'https://safe-go-98e43-default-rtdb.firebaseio.com',
    storageBucket: 'safe-go-98e43.appspot.com',
    iosBundleId: 'com.example.safeGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtZNhWv03Kl_da_vUoevW9RW52Vp7Gk9w',
    appId: '1:902496285809:ios:d3a2b13de97a4e84e957d0',
    messagingSenderId: '902496285809',
    projectId: 'safe-go-98e43',
    databaseURL: 'https://safe-go-98e43-default-rtdb.firebaseio.com',
    storageBucket: 'safe-go-98e43.appspot.com',
    iosBundleId: 'com.example.safeGo.RunnerTests',
  );
}
